In [112]:
import scipy.io as sio
import numpy as np
import pandas as pd

In [145]:
mat_fname1 = "./data/CountyMatrix_raw.mat"
mat_fname2 = "./data/CountyMatrix2010_v10.mat"
county_matx = sio.loadmat(mat_fname1, squeeze_me = True)

In [146]:
county_matx.keys()

dict_keys(['__header__', '__version__', '__globals__', 'col', 'd', 'fips'])

In [147]:
print(county_matx["col"].shape)
print(county_matx["d"].shape)
print(county_matx["fips"].shape)

(57,)
(3142, 57)
(3142,)


In [ ]:
### Not needed because of readmat squeezeme option
# this is the level where the column names exist, I think 
# county_matx["col"][0,1][0]

'Longitude'

In [ ]:
# col_names = []
# for c in range(0, county_matx["col"].shape[1]):
#     col_names.append(county_matx["col"][0,c][0])

# print(col_names)

['Lattitude', 'Longitude', 'Average Temperature Apr (2021)', 'Mean Temperature (1901-2000)', 'Total Medicare Reimbursements per Enrollee (2009)', 'Per Capita Income (Lst 12 MO, 2005-2009)', 'Cropland (sq mi, 2007)', 'Infant Deaths under 1 Year (2007)', 'Deaths (2007)', 'Births (2007)', 'Population over 85', 'Population over 75', 'Total Female Population', 'Single-Person Households (2005-2009)', 'Households with Perons under 18 Years', 'Total Veteran Population (2005-2009)', 'Hispanic or Latino Origin', 'Asian Alone Population', 'Native American and Alska Native Alone Population', 'Black Alone Population', 'White Alone Population', 'People of All Ages in Poverty (2009)', 'Number of Farms (2007)', "Total Per Capita Medicare Spending on Alzheimer's/Dementia", 'Land Area (sq mi)', 'Population over 65', 'Trump Votes (2016)', 'Population', 'Medicare: Alcohol Abuse Prevalence (%)', "Medicare: Alzheimer's Disease/Dementia Prevalence (%)", 'Medicare: Arthritis Prevalence (%)', 'Medicare: Asthma

In [ ]:
# county_matx["d"]

array([[  32.5349,  -86.6428,   63.2   , ...,   66.    ,   91.2   ,
              nan],
       [  30.7278,  -87.7171,   64.4   , ...,   47.9   ,   22.4   ,
              nan],
       [  31.8696,  -85.3932,   62.8   , ...,       nan,       nan,
              nan],
       ...,
       [  41.2876, -110.5476,   37.4   , ...,       nan,       nan,
              nan],
       [  43.905 , -107.6829,   40.3   , ...,       nan,       nan,
              nan],
       [  43.8404, -104.5679,   40.    , ...,       nan,       nan,
              nan]])

In [148]:
county_df = pd.DataFrame(data = county_matx["d"], columns=county_matx["col"])

In [149]:
county_df.head()

Lattitude  Longitude  Average Temperature Apr (2021)  \
0    32.5349   -86.6428                            63.2   
1    30.7278   -87.7171                            64.4   
2    31.8696   -85.3932                            62.8   
3    32.9986   -87.1264                            61.3   
4    33.9809   -86.5674                            60.2   

   Mean Temperature (1901-2000)  \
0                          63.6   
1                          66.4   
2                          64.5   
3                          62.5   
4                          60.3   

   Total Medicare Reimbursements per Enrollee (2009)  \
0                                           10146.32   
1                                           10018.91   
2                                            9979.23   
3                                           12040.00   
4                                           10755.04   

   Per Capita Income (Lst 12 MO, 2005-2009)  Cropland (sq mi, 2007)  \
0                                   23774.0               66.170312   
1                                   26197.0              160.993750   
2                                   15842.0               88.959375   
3                                   18953.0               13.467187   
4                                   20360.0               73.023438   

   Infant Deaths under 1 Year (2007)  Deaths (2007)  Births (2007)  ...  \
0                                6.0          406.0          719.0  ...   
1                               11.0         1682.0         2281.0  ...   
2                                6.0          248.0          417.0  ...   
3                                3.0          203.0          279.0  ...   
4                                7.0          542.0          720.0  ...   

   Medicare: Schizophrenia/Other Psychotic Disorders Prevalence (%)  \
0                                             1.7829                  
1                                             2.0338                  
2                                             2.2348                  
3                                             2.4417                  
4                                             2.4427                  

   Medicare: Stroke Prevalence (%)  WONDER: Alzheimer's Deaths  \
0                           4.6579                         NaN   
1                           4.4105                        20.8   
2                           5.0362                         NaN   
3                           4.1237                         NaN   
4                           4.5854                         NaN   

   WONDER: Ischemic Heart Disease Deaths  \
0                                  107.4   
1                                  105.6   
2                                    NaN   
3                                  192.5   
4                                   81.1   

   WONDER: Hypertensive Heart Disease Deaths  \
0                                        NaN   
1                                       26.0   
2                                        NaN   
3                                        NaN   
4                                        NaN   

   WONDER: Malignant Neoplasm Deaths  WONDER: Diabetes Deaths  \
0                              163.5                      NaN   
1                              181.6                     21.1   
2                              219.4                      NaN   
3                              239.9                      NaN   
4                              184.6                      NaN   

   WONDER: COPD Deaths  WONDER: Heart Failure Deaths  \
0                 66.0                          91.2   
1                 47.9                          22.4   
2                  NaN                           NaN   
3                  NaN                           NaN   
4                 60.6                          43.2   

   WONDER: Chronic Renal Disease Deaths  
0                                   NaN  
1                               

In [150]:
county_df["fips"] = county_matx["fips"]

In [151]:
county_df.head()

Lattitude  Longitude  Average Temperature Apr (2021)  \
0    32.5349   -86.6428                            63.2   
1    30.7278   -87.7171                            64.4   
2    31.8696   -85.3932                            62.8   
3    32.9986   -87.1264                            61.3   
4    33.9809   -86.5674                            60.2   

   Mean Temperature (1901-2000)  \
0                          63.6   
1                          66.4   
2                          64.5   
3                          62.5   
4                          60.3   

   Total Medicare Reimbursements per Enrollee (2009)  \
0                                           10146.32   
1                                           10018.91   
2                                            9979.23   
3                                           12040.00   
4                                           10755.04   

   Per Capita Income (Lst 12 MO, 2005-2009)  Cropland (sq mi, 2007)  \
0                                   23774.0               66.170312   
1                                   26197.0              160.993750   
2                                   15842.0               88.959375   
3                                   18953.0               13.467187   
4                                   20360.0               73.023438   

   Infant Deaths under 1 Year (2007)  Deaths (2007)  Births (2007)  ...  \
0                                6.0          406.0          719.0  ...   
1                               11.0         1682.0         2281.0  ...   
2                                6.0          248.0          417.0  ...   
3                                3.0          203.0          279.0  ...   
4                                7.0          542.0          720.0  ...   

   Medicare: Stroke Prevalence (%)  WONDER: Alzheimer's Deaths  \
0                           4.6579                         NaN   
1                           4.4105                        20.8   
2                           5.0362                         NaN   
3                           4.1237                         NaN   
4                           4.5854                         NaN   

   WONDER: Ischemic Heart Disease Deaths  \
0                                  107.4   
1                                  105.6   
2                                    NaN   
3                                  192.5   
4                                   81.1   

   WONDER: Hypertensive Heart Disease Deaths  \
0                                        NaN   
1                                       26.0   
2                                        NaN   
3                                        NaN   
4                                        NaN   

   WONDER: Malignant Neoplasm Deaths  WONDER: Diabetes Deaths  \
0                              163.5                      NaN   
1                              181.6                     21.1   
2                              219.4                      NaN   
3                              239.9                      NaN   
4                              184.6                      NaN   

   WONDER: COPD Deaths  WONDER: Heart Failure Deaths  \
0                 66.0                          91.2   
1                 47.9                          22.4   
2                  NaN                           NaN   
3                  NaN                           NaN   
4                 60.6                          43.2   

   WONDER: Chronic Renal Disease Deaths  fips  
0                                   NaN  1001  
1                                   NaN  1003  
2                                   NaN  1005  
3                                   NaN  1007  
4                                   NaN  1009  

[5 rows x 58 columns]

In [143]:
pest_fname1 = "./data/pesticides2010_kgperarea2.mat"
pest_matx = sio.loadmat(pest_fname1,squeeze_me = True)

In [144]:
pest_matx.keys()
print(pest_matx["cols"].shape)
print(pest_matx["cols"])
print(pest_matx["fips"].shape)
print(pest_matx["fips"])
print(pest_matx["pest"].shape)
print(pest_matx["pest"])


(385,)
['2,4-D' '2,4-DB' '6-BENZYLADENINE' 'ABAMECTIN' 'ACEPHATE' 'ACEQUINOCYL'
 'ACETAMIPRID' 'ACETOCHLOR' 'ACIBENZOLAR' 'ACIFLUORFEN' 'ALACHLOR'
 'ALDICARB' 'ALUMINUM PHOSPHIDE' 'AMETRYN' 'AMINOPYRALID' 'ASULAM'
 'ATRAZINE' 'AVIGLYCINE' 'AZADIRACHTIN' 'AZINPHOS-METHYL' 'AZOXYSTROBIN'
 'BACILLUS CEREUS' 'BACILLUS FIRMUS' 'BACILLUS PUMILIS'
 'BACILLUS SUBTILIS' 'BACILLUS THURINGIENSIS' 'BENFLURALIN' 'BENOMYL'
 'BENSULFURON' 'BENSULIDE' 'BENTAZONE' 'BIFENAZATE' 'BIFENTHRIN'
 'BISPYRIBAC' 'BORDEAUX MIXTURE' 'BOSCALID' 'BROMACIL' 'BROMOXYNIL'
 'BUPROFEZIN' 'BUTRALIN' 'BUTYLATE' 'CALCIUM POLYSULFIDE' 'CAPTAN'
 'CARBARYL' 'CARBOFURAN' 'CARBOPHENOTHION' 'CARBOXIN'
 'CARFENTRAZONE-ETHYL' 'CHINOMETHIONAT' 'CHLORAMBEN' 'CHLORANTRANILIPROLE'
 'CHLORETHOXYFOS' 'CHLORFENAPYR' 'CHLORIDAZON' 'CHLORIMURON' 'CHLORMEQUAT'
 'CHLORONEB' 'CHLOROPICRIN' 'CHLOROTHALONIL' 'CHLORPROPHAM' 'CHLORPYRIFOS'
 'CHLORSULFURON' 'CLETHODIM' 'CLODINAFOP' 'CLOFENTEZINE' 'CLOMAZONE'
 'CLOPYRALID' 'CLORANSULAM-METHYL' 'CLO

In [152]:
dis_matx = sio.loadmat("./data/dis.mat", squeeze_me = True)
dis_matx.keys()

dict_keys(['__header__', '__version__', '__globals__', 'c', 'd', 'nd', 'r'])

In [153]:
# this is a dataset containing disease incidence by state 
print(dis_matx["c"].shape)
print(dis_matx["c"])
print(dis_matx["d"].shape)
print(dis_matx["d"])
print(dis_matx["nd"].shape)
print(dis_matx["nd"])
print(dis_matx["r"].shape)
print(dis_matx["r"])


(41,)
['Campylobacteriosis' 'Chlamydia trachomatis infection'
 'Coronavirus Disease 2019 (COVID-19), Total' 'Cryptosporidiosis, Total'
 'Gonorrhea'
 'Haemophilus influenzae, invasive disease, All ages, all serotypes'
 'Hepatitis, A' 'Hepatitis, B, acute' 'Hepatitis, C, acute'
 'Human immunodeficiency virus diagnoses'
 'Influenza-associated pediatric mortality' 'Legionellosis'
 'Listeriosis, Total' 'Lyme disease, Total' 'Malaria' 'Mumps' 'Pertussis'
 'Rabies, Animal'
 'Salmonellosis (excluding S. Typhi infection and S. Paratyphi infection)'
 'Shiga toxin-producing Escherichia coli (STEC)' 'Shigellosis'
 'Spotted fever rickettsiosis, Total' 'Syphilis, Total, all stages'
 'Tuberculosis' 'Vibriosis, Total' '#Alzheimer disease (G30)'
 '#COVID-19 (U07.1)' '#Cerebrovascular diseases (I60-I69)'
 '#Chronic liver disease and cirrhosis (K70,K73-K74)'
 '#Chronic lower respiratory diseases (J40-J47)'
 '#Congenital malformations, deformations and chromosomal abnormalities (Q00-Q99)'
 '#Diabetes mell

In [140]:
geodemo = sio.loadmat("./data/geodemo.mat")
geodemo.keys()

dict_keys(['__header__', '__version__', '__globals__', 'conds', 'd', 'nd', 'states'])

In [141]:
print(geodemo["d"].shape)
print(geodemo["d"])
print(geodemo["nd"].shape)
print(geodemo["nd"])
print(geodemo["conds"].shape)
print(geodemo["conds"])
print(geodemo["states"].shape)

(48, 24)
[[  43.8    96.2    40.1  ...   64.9  1987.     68.67]
 [  37.6    95.4    36.8  ...   62.6  3557.      6.56]
 [  47.9    96.4    34.9  ...   61.2  1604.     63.82]
 ...
 [  32.8    95.     36.6  ...   54.    873.     53.77]
 [  43.1    96.7    41.4  ...   44.8   605.     34.19]
 [  42.5    96.3    37.6  ...   42.8   356.     11.72]]
(48, 24)
[[-0.30973133 -0.08730791 -0.02870318 ...  1.4053645   0.91727465
   1.56311595]
 [-1.20900979 -1.10325445 -0.79931066 ...  1.1105664   2.73978033
  -1.67737576]
 [ 0.28495282  0.16667873 -1.24299376 ...  0.93112408  0.47267613
   1.31007482]
 ...
 [-1.90522538 -1.61122772 -0.84601415 ...  0.00827785 -0.3758918
   0.78573185]
 [-0.41126277  0.54765868  0.27486946 ... -1.17091456 -0.68699467
  -0.2358239 ]
 [-0.49828971  0.03968541 -0.61249673 ... -1.42726074 -0.97604175
  -1.40816086]]
(1, 24)
[[array(['a1'], dtype='<U2') array(['a2'], dtype='<U2')
  array(['a3'], dtype='<U2') array(['b1'], dtype='<U2')
  array(['b2'], dtype='<U2') array(

want to answer a question about the fips codes, because in the pest dataset online it appears that they're stored with thier state and county could, with the county codes being none unique

In [ ]:
county_df["fips"].unique()

array([ 1001,  1003,  1005, ..., 56041, 56043, 56045], dtype=uint16)

so it appears that to make the fips codes they just combined both of the state and county codes. I will try to recreate just the pesticide data and then save it as a csv 

In [156]:
# now i can finally combine the pesticide and county data 
county_df.head()
print(county_df.shape)


(3142, 58)


In [ ]:
#read csv 
pest_df = pd.read_csv("./data/pesticide_data_2010.csv")

# get rid of first row 
pest_df.drop(["Unnamed: 0"],axis=1, inplace=True )






In [179]:
np.set_printoptions(threshold=np.inf)
print(np.unique(pest_df["FIPS"]))
print(np.unique(county_df["fips"]))

[ 1001  1003  1005  1007  1009  1011  1013  1015  1017  1019  1021  1023
  1025  1027  1029  1031  1033  1035  1037  1039  1041  1043  1045  1047
  1049  1051  1053  1055  1057  1059  1061  1063  1065  1067  1069  1071
  1073  1075  1077  1079  1081  1083  1085  1087  1089  1091  1093  1095
  1097  1099  1101  1103  1105  1107  1109  1111  1113  1115  1117  1119
  1121  1123  1125  1127  1129  1131  1133  4001  4003  4005  4007  4009
  4011  4012  4013  4015  4017  4019  4021  4023  4025  4027  5001  5003
  5005  5007  5009  5011  5013  5015  5017  5019  5021  5023  5025  5027
  5029  5031  5033  5035  5037  5039  5041  5043  5045  5047  5049  5051
  5053  5055  5057  5059  5061  5063  5065  5067  5069  5071  5073  5075
  5077  5079  5081  5083  5085  5087  5089  5091  5093  5095  5099  5101
  5103  5105  5107  5109  5111  5113  5115  5117  5119  5121  5123  5125
  5127  5129  5131  5133  5135  5137  5139  5141  5143  5145  5147  5149
  6001  6003  6005  6007  6009  6011  6013  6015  6

In [184]:
# which ones are missing 
missing_counties = []
FIPS = np.unique(pest_df["FIPS"]) 
for x in np.unique(county_df["fips"]):
    if x not in FIPS: 
        missing_counties.append(x)

In [185]:
missing_counties 

[2013,
 2016,
 2020,
 2050,
 2060,
 2068,
 2070,
 2090,
 2100,
 2110,
 2122,
 2130,
 2150,
 2164,
 2170,
 2180,
 2185,
 2188,
 2201,
 2220,
 2232,
 2240,
 2261,
 2270,
 2280,
 2282,
 2290,
 5097,
 8111,
 11001,
 15001,
 15003,
 15007,
 15009,
 24510,
 29510,
 30113,
 34017,
 36005,
 36061,
 36085,
 51013,
 51510,
 51515,
 51520,
 51530,
 51540,
 51560,
 51570,
 51580,
 51590,
 51595,
 51600,
 51610,
 51620,
 51630,
 51640,
 51650,
 51660,
 51670,
 51678,
 51680,
 51683,
 51685,
 51690,
 51700,
 51710,
 51720,
 51730,
 51735,
 51740,
 51750,
 51760,
 51770,
 51775,
 51780,
 51790,
 51820,
 51830,
 51840]

In [ ]:
full_df = pd.merge(county_df, pest_df, how="left", left_on = "fips", right_on = "FIPS")

In [166]:
print(pest_df.shape)
print(county_df.shape)
print(full_df.shape)

(3063, 386)
(3142, 58)
(3142, 444)


In [ ]:
# print(full_df.columns)

print( [col for col in full_df.columns])


['Lattitude', 'Longitude', 'Average Temperature Apr (2021)', 'Mean Temperature (1901-2000)', 'Total Medicare Reimbursements per Enrollee (2009)', 'Per Capita Income (Lst 12 MO, 2005-2009)', 'Cropland (sq mi, 2007)', 'Infant Deaths under 1 Year (2007)', 'Deaths (2007)', 'Births (2007)', 'Population over 85', 'Population over 75', 'Total Female Population', 'Single-Person Households (2005-2009)', 'Households with Perons under 18 Years', 'Total Veteran Population (2005-2009)', 'Hispanic or Latino Origin', 'Asian Alone Population', 'Native American and Alska Native Alone Population', 'Black Alone Population', 'White Alone Population', 'People of All Ages in Poverty (2009)', 'Number of Farms (2007)', "Total Per Capita Medicare Spending on Alzheimer's/Dementia", 'Land Area (sq mi)', 'Population over 65', 'Trump Votes (2016)', 'Population', 'Medicare: Alcohol Abuse Prevalence (%)', "Medicare: Alzheimer's Disease/Dementia Prevalence (%)", 'Medicare: Arthritis Prevalence (%)', 'Medicare: Asthma

In [186]:
full_df.to_csv("full_dataset_v1")